# Generated by Django 5.1.6 on 2025-05-17 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Promotion Categories',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('product_names', models.JSONField(blank=True, default=list, null=True)),
                ('product_data', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='businesses.business')),
                ('categories', models.ManyToManyField(related_name='promotions', to='promotions.promotioncategories')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_names', models.JSONField(blank=True, default=list, null=True)),
                ('product_data', models.JSONField(blank=True, default=list, null=True)),
                ('data_start_date', models.DateField(blank=True, null=True)),
                ('data_end_date', models.DateField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='businesses.business')),
                ('categories', models.ManyToManyField(related_name='suggestions', to='promotions.promotioncategories')),
            ],
            options={
                'verbose_name_plural': 'Promotion Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
