services:
  - name: backend
    type: web
    runtime: docker
    env: docker
    repo: https://github.com/heeran-kim/ai-marketer-v2
    branch: main
    plan: free
    dockerfilePath: ai-marketer-v2-backend/backend/Dockerfile.render
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: DJANGO_ENV
        value: "production"
      - key: FLUSH_DB
        value: "False"
      - key: USE_RENDER_DB
        value: "True"
      - key: TEMP_MEDIA_DISCORD_WEBHOOK
        value: "True"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://ai-marketer-v2.vercel.app"
      - key: FRONTEND_BASE_URL
        value: "https://ai-marketer-v2.vercel.app"
      - key: SQUARE_ENV
        value: "production"
      - key: SQUARE_BASE_URL_SANDBOX
        value: "https://connect.squareupsandbox.com"
      - key: SQUARE_BASE_URL_PROD
        value: "https://connect.squareup.com"
      - key: SQUARE_REDIRECT_URI
        value: "https://backend-0vrq.onrender.com/api/businesses/square/callback/"
      - key: FACEBOOK_REDIRECT_URI
        value: "https://ai-marketer-v2.vercel.app/settings/social/"
      - key: CELERY_BROKER_URL
        fromService:
          name: redis
          type: redis
          property: connectionString

  - name: redis
    type: redis
    plan: free
    ipAllowList:
      - source: backend
        description: Allow backend to access Redis

databases:
  - name: postgres
    plan: free
