FROM python:3.11

WORKDIR /app
COPY /ai-marketer-v2-backend/backend /app

RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["sh", "-c", "gunicorn --workers 1 --timeout 60 --bind 0.0.0.0:8000 backend.wsgi:application & celery -A config.celery_app worker --loglevel=info --concurrency=1"]
