FROM python:3.11

WORKDIR /app
COPY /ai-marketer-v2-backend/backend /app

RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["sh", "-c", "exec gunicorn --workers 2 --timeout 120 --bind 0.0.0.0:8000 backend.wsgi:application"]